mybatis:
  type-aliases-package: com.rcplatformhk.userpoolserver.dao.entity
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.100.73.91:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: rc_2019_good
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 12
        max-wait: 1
        max-idle: 12
        min-idle: 0
    timeout: 15000
    commandTimeout: 5000
thread:
  size: 4
