mybatis:
  type-aliases-package: com.rcplatformhk.userpoolserver.com.rcplatformhk.us.dao.entity
spring:
  redis:
    database: 0
    password:
    lettuce:
      pool:
        max-active: 12
        max-wait: 1
        max-idle: 12
        min-idle: 0
    timeout: 15000
    commandTimeout: 5000
    cluster:
      nodes: 172.26.220.197:6379, 172.26.220.197:6380, 172.26.220.197:6381
datasource:
  jdbc:
    driverClassName: com.mysql.jdbc.Driver
    url_major: jdbc:mysql://172.26.220.198:3306/rc_video_chat?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username_major: testdb
    password_major: mofnuWs2YZvLMed&12VKmVFr
    url_secondary: jdbc:mysql://172.26.220.198:3306/rc_live_chat_statistics?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username_secondary: testdb
    password_secondary: mofnuWs2YZvLMed&12VKmVFr
thread:
  size: 4
logging:
  config: classpath:log4j2-spring.xml