mybatis:
  type-aliases-package: com.rcplatformhk.userpoolserver.com.rcplatformhk.us.dao.entity
spring:
#  datasource:
#    driverClassName: com.mysql.jdbc.Driver
#    url: jdbc:mysql://39.100.73.91:3306/rc_video_chat?useUnicode=true&characterEncoding=utf-8&useSSL=false
#    username: root
#    password: rc_2019_good
  redis:
    database: 0
    password:
    lettuce:
      pool:
        max-active: 12
        max-wait: 1
        max-idle: 12
        min-idle: 0
    timeout: 15000
    commandTimeout: 5000
    cluster:
      nodes: 127.0.0.1:6379, 127.0.0.1:6380, 127.0.0.1:6381
datasource:
  jdbc:
    driverClassName: com.mysql.jdbc.Driver
    url_major: jdbc:mysql://47.92.116.139:3306/rc_video_chat?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username_major: testdb
    password_major: mofnuWs2YZvLMed&12VKmVFr
    url_secondary: jdbc:mysql://47.92.116.139:3306/rc_live_chat_statistics?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username_secondary: testdb
    password_secondary: mofnuWs2YZvLMed&12VKmVFr
thread:
  size: 4
logging:
  config: classpath:log4j2-spring.xml