mybatis:
  type-aliases-package: com.rcplatformhk.userpoolserver.com.rcplatformhk.us.dao.entity
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.26.220.198:3306/rc_video_chat?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: testdb
    password: mofnuWs2YZvLMed&12VKmVFr
  redis:
    database: 0
    host: 172.26.220.197
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 12
        max-wait: 1
        max-idle: 12
        min-idle: 0
    timeout: 15000
    commandTimeout: 5000
thread:
  size: 4
logging:
  config: classpath:log4j2-spring.xml